TokenInfo(type=65 (ENCODING), string='utf-8', start=(0, 0), end=(0, 0), line=''),
TokenInfo(type=1 (NAME), string='import', start=(1, 0), end=(1, 6), line='import sys\n'),
TokenInfo(type=1 (NAME), string='sys', start=(1, 7), end=(1, 10), line='import sys\n'),
TokenInfo(type=4 (NEWLINE), string='\n', start=(1, 10), end=(1, 11), line='import sys\n'),
TokenInfo(type=1 (NAME), string='from', start=(2, 0), end=(2, 4), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='tokenize', start=(2, 5), end=(2, 13), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='import', start=(2, 14), end=(2, 20), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='tokenize', start=(2, 21), end=(2, 29), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=55 (OP), string=',', start=(2, 29), end=(2, 30), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='tok_name', start=(2, 31), end=(2, 39), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=55 (OP), string=',', start=(2, 39), end=(2, 40), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='INDENT', start=(2, 41), end=(2, 47), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=55 (OP), string=',', start=(2, 47), end=(2, 48), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='DEDENT', start=(2, 49), end=(2, 55), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=55 (OP), string=',', start=(2, 55), end=(2, 56), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='NAME', start=(2, 57), end=(2, 61), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=55 (OP), string=',', start=(2, 61), end=(2, 62), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='TokenInfo', start=(2, 63), end=(2, 72), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=4 (NEWLINE), string='\n', start=(2, 72), end=(2, 73), line='from tokenize import tokenize, tok_name, INDENT, DEDENT, NAME, TokenInfo\n'),
TokenInfo(type=1 (NAME), string='tokenfile', start=(3, 0), end=(3, 9), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=55 (OP), string='=', start=(3, 10), end=(3, 11), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=1 (NAME), string='open', start=(3, 12), end=(3, 16), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=55 (OP), string='(', start=(3, 16), end=(3, 17), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=1 (NAME), string='sys', start=(3, 17), end=(3, 20), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=55 (OP), string='.', start=(3, 20), end=(3, 21), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=1 (NAME), string='argv', start=(3, 21), end=(3, 25), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=55 (OP), string='[', start=(3, 25), end=(3, 26), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=2 (NUMBER), string='0', start=(3, 26), end=(3, 27), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=55 (OP), string=']', start=(3, 27), end=(3, 28), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=55 (OP), string=',', start=(3, 28), end=(3, 29), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=3 (STRING), string="'rb'", start=(3, 30), end=(3, 34), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=55 (OP), string=')', start=(3, 34), end=(3, 35), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=4 (NEWLINE), string='\n', start=(3, 35), end=(3, 36), line="tokenfile = open(sys.argv[0], 'rb')\n"),
TokenInfo(type=1 (NAME), string='tokens', start=(4, 0), end=(4, 6), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=55 (OP), string='=', start=(4, 7), end=(4, 8), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=1 (NAME), string='list', start=(4, 9), end=(4, 13), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=55 (OP), string='(', start=(4, 13), end=(4, 14), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=1 (NAME), string='tokenize', start=(4, 14), end=(4, 22), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=55 (OP), string='(', start=(4, 22), end=(4, 23), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=1 (NAME), string='tokenfile', start=(4, 23), end=(4, 32), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=55 (OP), string='.', start=(4, 32), end=(4, 33), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=1 (NAME), string='readline', start=(4, 33), end=(4, 41), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=55 (OP), string=')', start=(4, 41), end=(4, 42), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=55 (OP), string=')', start=(4, 42), end=(4, 43), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=4 (NEWLINE), string='\n', start=(4, 43), end=(4, 44), line='tokens = list(tokenize(tokenfile.readline))\n'),
TokenInfo(type=1 (NAME), string='print', start=(5, 0), end=(5, 5), line='print(tokens)'),
TokenInfo(type=55 (OP), string='(', start=(5, 5), end=(5, 6), line='print(tokens)'),
TokenInfo(type=1 (NAME), string='tokens', start=(5, 6), end=(5, 12), line='print(tokens)'),
TokenInfo(type=55 (OP), string=')', start=(5, 12), end=(5, 13), line='print(tokens)'),
TokenInfo(type=4 (NEWLINE), string='', start=(5, 13), end=(5, 14), line='print(tokens)'),
TokenInfo(type=0 (ENDMARKER), string='', start=(6, 0), end=(6, 0), line='')